name: Auto Increment Commit Message

on:
  push:
    branches:
      - main 

jobs:
  increment-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        persist-credentials: false  

    - name: Get latest commit message
      id: get_commit
      run: |
        latest_commit_msg=$(git log -1 --pretty=%B)
        echo "Latest commit message: $latest_commit_msg"
        echo "::set-output name=msg::$latest_commit_msg"

    - name: Increment day number and commit changes
      env:
        LAST_MSG: ${{ steps.get_commit.outputs.msg }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Extract number from commit msg like day_14
        if [[ "$LAST_MSG" =~ day_([0-9]+) ]]; then
          num=${BASH_REMATCH[1]}
          next_num=$((num + 1))
        else
          # Default start if no match found
          next_num=1
        fi
        new_msg="day_${next_num}"
        echo "New commit message: $new_msg"

        # Make sure you have changes to commit, for demo create a dummy file with timestamp
        echo "Automated commit for $new_msg" > day.txt
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add day.txt
        git commit -m "$new_msg"
        git push origin HEAD:main
